version: '3.5'

services:
  db:
    image: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: QoinDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    